
# Deployment for Makeline Service  for Azure Servie Bus
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 1 # Single replica
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: makeline-service
          image: bhun0002/makeline-service-best-buy:latest # Custom Makeline service image
          ports:
            - containerPort: 3001 # Makeline service listens on this port
          env: # Environment variables for configuration
            - name: ORDER_QUEUE_URI
              value: "amqps://bestbuybusservice.servicebus.windows.net/" # Your Azure Bus Service Host Name  
            - name: ORDER_QUEUE_USERNAME
              value: "listener"  # Authorization rule name
            - name: ORDER_QUEUE_PASSWORD
              value: "irFnlJLM/XZAbK/7hZhf21w2WV7yq/8zf+ASbDUyMhQ=" # Replace with the actual primary key
            - name: ORDER_QUEUE_NAME
              value: "orders"
            - name: USE_WORKLOAD_IDENTITY_AUTH
              value: "true" # Set to "true" if using Azure Workload Identity
            - name: ORDER_QUEUE_TRANSPORT
              value: "tls" 
            - name: ORDER_QUEUE_RECONNECT_LIMIT
              value: "3"  
            - name: ORDER_DB_URI
              value: "mongodb://mongodb:27017" # MongoDB connection string
            - name: ORDER_DB_NAME
              value: "orderdb" # Database name
            - name: ORDER_DB_COLLECTION_NAME
              value: "orders" # Collection name
          resources: # Resource requests and limits
            requests:
              cpu: 1m
              memory: 6Mi
            limits:
              cpu: 5m
              memory: 20Mi
          startupProbe: # Initial health check
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 10
            periodSeconds: 5
          readinessProbe: # Ready status probe
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe: # Ongoing health check
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
---
# Service for Makeline Service
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  type: ClusterIP # Internal cluster service
  ports:
    - name: http
      port: 3001 # Service port
      targetPort: 3001
  selector:
    app: makeline-service
---
